{
    "name": "Payment remittance",
    "version": "18.0.1.0.0",
    "description": "Module for managing payment remittances for Accounts payable",
    "summary": "This module is used to manage remittances",
    "author": "FTNMX",
    "website": "https://formalizatunegocio.com",
    "license": "LGPL-3",
    "category": "Accounting",
    "depends": ["mail", "purchase", "account", "l10n_mx_sat_sync_itadmin"],
    'images': ['static/description/icon.png'],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "data/remittance_stage_data.xml",
        "report/account_remittance_report.xml",
        "views/remittance_stage_views.xml",
        "wizards/account_remittance_export_wizard.xml",
        "wizards/account_remittance_generate_wizard.xml",
        "wizards/account_register_payment_wizard.xml",
        "views/account_remittance_views.xml",
        "report/account_remittance_templates.xml",
        "views/analytic_view.xml",
    ],
    "auto_install": False,
    "application": True,
    'assets': {
        'web.assets_backend': [
            'ftn_remittance/static/src/js/generate_remittance_views.js',
            'ftn_remittance/static/src/js/generate_remittance_hook.js',
            'ftn_remittance/static/src/xml/generate_remittance_buttons.xml',
        ],
    },
}
